# Generated by Django 5.0 on 2023-12-13 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Drinks",
            new_name="Drink",
        ),
    ]
